### ISSUE TITLE
Users must create account on creepshield.com

### ISSUE THREAD

**Issue by Servelan** [meitar/pat-okcupid#19]
Firefox v. 30, latest pat-okcupid; by default, only 3 anonymous facial recognition attempts are allowed by creepshield.com unless the user logs in, requiring an account.  Process: Install PAT-OKC, create account on creepshield and log into creepshield.  Log into OKC, answer PAC-OKC questions, look at profiles.  In future, log into creepshield first, then surf OKC.  Documentable.

**Comment by Servelan** [comment]
Isn't
    working as described on Firefox 30.  Pops up an error...maybe
    not a problem on Chrome, but a problem on Firefox 30.  
    Totally agree about prison-industrial complex, but

**Comment by Servelan** [comment]
Let me
    finish my thought...
    Totally agree about prison-industrial complex, but - there has
    to be a balance between my safety and political activism.  Not
    saying that people *should* make accounts, but it is a
    workaround.  Quickmatch tosses a lot of people at the user, and
    having to stop at 3 isn't obvious or made aware to the user in
    any way unless they open a tab and go to the face recog site,
    which I did.
    If all you do is document this, cool (just the part about maybe
    a problem with Firefox/anonymous searches/cookie settings).  If
    my cookies don't crumble when they should, not much I can do
    about that unless there's some setting users can tweak.

**Comment by Servelan** [comment]
Agreed,
    that is *expected* behavior, but  not what I'm experiencing.
    User FriendofMrCairo answered the 'no means no'
    question...badly.  Also, Creepshield error displays.  After
    reloading the page, same creepshield error.  Repeatedly.  
    User GoodFunandKind didn't answer any questions in an alarming
    manner (except he thinks creationism should be taught along with
    evolution...which I've tagged as one of my personal red flags,
    which doesn't show up as a PAT 'alarm'), but same Creepshield
    error. 
    I'm expecting the expected behavior, but all I get is
    'creepshield error'.  Somehow I also get a tab with Creepshield
    itself telling me 'you had your three anonymous checks, now log
    in'.
    I log in to creepshield itself, no more errors.  Plus, for
    GoodFunandKind, clicking on the 64% RSO match info on his
    profile page now pops up a gnarly looking dude who obviously
    isn't GoodFunandKind (meaning it works to return data once I log
    in to creepshield).
    So...I know that it's *supposed* to work, but it isn't on
    Firefox 30.  If there's some setting I could tweak that would
    make a difference, I would, but I'm accepting all cookies and
    even third party cookies and that's all I know to do with
    cookies...

**Comment by Servelan** [comment]
What I see
    displayed on a profile page is 'creepshield error'; if I click
    on that, then the message box appears that says 'refresh this
    page if you get the 'log in' message.  On the creepshield page
    that appears, it says 'log in to do more searches'.
    As for the other thing, I suspect that until the dialog box that
    appears when you click 'add to my red flags' is fixed so that it
    shows the answers for the question and the user can select which
    answers are alarming, it's not possible to deal with as a
    separate bug; I'm guessing it's dependent behavior.  
    Found another user with several personal red flags, however, so
    am ready to test out any fix you come up with.

**Comment by Servelan** [comment]
Ok, it's
    late and my turn to be confused...'Yes'....what?  Do you want me
    to report on the issue of PAT-OKC not returning my personal red
    flags, even though the dialog itself has issues that may be
    causing that problem by not showing the answers for the user to
    select?  Or do you want me to re-write the two bugs on Github
    more formally?  
    I was telling you with my last e-mail I've got test cases, as it
    were, so if/when the dialog/code is modified to address the
    issue, I can, if you would like me to, try to repro the problem
    with my three sets of user data, with PAT answers, with PAT
    answers plus my personal red flags, and with only my red flags. 
    I can't think of another combination of data that would be
    needed...I would think that if the dialog shows the answers so
    that the user can select which are alarming - kind of looks like
    it's trying to do that around line 838? (it does say it saves my
    selection of the question itself, btw) that the script would
    then have something to return to the user rather than just the
    question itself having been chosen.

**Comment by meitar** [comment]
CreepShield.com no longer exists, so this issue is no longer relevant.
